import { DataTypes } from "sequelize";

export default(sequelize)=>{
    const FinalInvoice = sequelize.define(
        'FinalInvoice' ,{
            id:{
                type:DataTypes.UUID,
                defaultValue:DataTypes.UUIDV4,
                primaryKey:true
            },
            invoiceNumber:{
                type:DataTypes.STRING(50),
                allowNull:false,
                unique:true
            },
            clientId:{
                type:DataTypes.UUID,
                allowNull:false
            },
            proformaInvoiceId:{
                type:DataTypes.UUID,
                allowNull:true
            },
            status:{
                type:DataTypes.ENUM(
                    'draft',
                    'paid',
                    'sent',
                    'overdue',
                    'partially_paid'
                ),
                defaultValue:'draft'
            },
            invoiceDate:{
                type:DataTypes.DATEONLY,
                allowNull:false
            },
            dueDate:{
                type:DataTypes.DATEONLY,
                allowNull:true
            },
            subtotal:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            gstAmount:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            cgst:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            sgst:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            igst:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            discount:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            totalAmount:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            paidAmount:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            dueAmount:{
                type:DataTypes.DECIMAL(15,2),
                defaultValue:0
            },
            currency:{
                type:DataTypes.STRING(10),
                defaultValue:'INR'
            },
            notes:{
                type:DataTypes.TEXT,
                allowNull:true
            },
            termsAndConditions:{
                type:DataTypes.TEXT,
                allowNull:true
            },
            sentAt:{
                type:DataTypes.DATE,
                allowNull:true
            },
            paidAt:{
                type:DataTypes.DATE,
                allowNull:true
            },
        },
        {      
              tableName:'final_invoices',
            paranoid:true
        }
    )
    return FinalInvoice;
};